name: Playbook initilastion

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository:  priyesh2/devops-flask
         
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     
    - name: testing secrets
      env:
         VAULT_PASS: ${{ secrets.VAULT_PASS }}
      run: echo $VAULT_PASS >> secret.txt
        
    - name: running playbook 
      run: ansible-vault decrypt docker.vars --vault-password-file=vault.txt && ansible-playbook docker.yml
      
    
