name: Playbook initilastion

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository:  priyesh2/devops-flask
         
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: running playbook 
      run: ansible-playbook --extra-vars "username=$secrets.DOCKERHUB_USERNAME" "password=$secrets.DOCKERHUB_TOKEN" docker.yml
      
    
