name: Playbook initilastion

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository:  priyesh2/devops-flask
         
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: running playbook 
      run: ansible-playbook --connection=local --inventory 127.0.0.1 --limit 127.0.0.1 docker.yml -i ansible_hosts
      
    
